import { useMemo, useState } from "react";
import { fillPrompt, chatGPTUrl, claudeUrl } from "../lib/prompt";

export const PLAN_INITIAL = {
  decisions: "",
  goals30: "",
  goals60: "",
  goals90: "",
  goals120: "",
  goals180: "",
};

const GOAL_FIELDS = [
  {
    key: "goals30",
    label: "🎯 30 days",
    hint: "First month — what's true if you've launched? Usually: page live, first 10 signups, first conversation with a real customer.",
    placeholder: "e.g. Live landing page with 25 signups. 5 customer interviews. First $1 of revenue.",
  },
  {
    key: "goals60",
    label: "🎯 60 days",
    hint: "Month 2 — what's true if early traction is real? Usually: first paying customers, repeatable channel.",
    placeholder: "e.g. 5 paying customers at $25/mo = $125 MRR. One channel that reliably brings 1+ signup per day.",
  },
  {
    key: "goals90",
    label: "🎯 90 days",
    hint: "End of Q1 — first quarterly Go / No-Go / Pivot decision point. Are the numbers trending toward the goal?",
    placeholder: "e.g. 15 paying customers, $375 MRR, retention rate measured. Decided: GO / NO-GO / PIVOT.",
  },
  {
    key: "goals120",
    label: "🎯 120 days",
    hint: "Month 4 — what's true if you're really on a path? Look for early word-of-mouth or referrals.",
    placeholder: "e.g. 25 paying customers, $625 MRR, first referral customer, monthly Feasibility Analysis green across all 3 lenses.",
  },
  {
    key: "goals180",
    label: "🎯 180 days — the $1,000/month finish line",
    hint: "6-month mark. The original goal. What does success look like at the cohort's end?",
    placeholder: "e.g. 40 paying customers at $25/mo = $1,000 MRR. Clear next milestone defined. Decided: scale, lifestyle business, or close.",
  },
];

function buildAIPrompt(profile) {
  const lines = [];
  lines.push(`Draft 5 honest milestone goals for [insert idea] over the next 6 months. The North Star is $1,000/month in revenue by day 180.`);
  lines.push("");
  lines.push(`Venture context:`);
  lines.push(`- What it is: [insert idea]`);
  lines.push(`- Target customer: [audience]`);
  lines.push(`- Market area: [market area]`);
  lines.push(`- Core offer: [core value proposition]`);
  lines.push("");
  lines.push(`Format as five blocks. For each, use this exact structure:`);
  lines.push("");
  lines.push(`**[N] DAYS:**`);
  lines.push(`- Top metric: <single number to track>`);
  lines.push(`- 3 SMART goals (Specific, Measurable, Achievable, Relevant, Time-bound)`);
  lines.push(`- 1 leading indicator I should watch weekly`);
  lines.push(`- 1 thing to STOP doing`);
  lines.push("");
  lines.push(`Timeframes: 30, 60, 90, 120, 180 days.`);
  lines.push("");
  lines.push(`Be realistic — don't pad. Day 30 should focus on validation and the first paying customer; day 60 on a repeatable channel; day 90 is the first Go/No-Go/Pivot decision; day 120 on retention and referrals; day 180 is the $1,000/month finish line.`);
  return lines.join("\n");
}

function buildPlanMarkdown(profile, plan) {
  const today = new Date().toISOString().slice(0, 10);
  const lines = [];
  lines.push(`# ${profile?.ideaName || "Your Venture"} — Plan & Goals`);
  if (profile?.teamName) lines.push(`**Team:** ${profile.teamName}`);
  lines.push(`**Exported:** ${today}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`## 📌 Decisions Log`);
  lines.push("");
  if (plan.decisions && plan.decisions.trim()) {
    lines.push(plan.decisions.trim());
  } else {
    lines.push(`_(no decisions captured yet)_`);
  }
  lines.push("");
  lines.push("---");
  lines.push("");
  lines.push(`## 🎯 6-Month Milestone Goals`);
  lines.push("");
  for (const f of GOAL_FIELDS) {
    const value = (plan[f.key] || "").trim();
    lines.push(`### ${f.label}`);
    lines.push("");
    if (value) {
      lines.push(value);
    } else {
      lines.push(`_(not set)_`);
    }
    lines.push("");
  }
  lines.push("---");
  lines.push("");
  lines.push(`_Generated by the COD AI Startup Weekend tool._`);
  return lines.join("\n");
}

function slugify(text) {
  return (text || "")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .slice(0, 40);
}

function downloadPlan(profile, plan) {
  const md = buildPlanMarkdown(profile, plan);
  const today = new Date().toISOString().slice(0, 10);
  const base = slugify(profile?.teamName) || slugify(profile?.ideaName) || "team";
  const filename = `cod-startup-plan-${base}-${today}.md`;
  const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

function hasGoals(plan) {
  return GOAL_FIELDS.some((f) => (plan[f.key] || "").trim().length > 0);
}

export default function Plan({ profile, plan, onChange }) {
  const [open, setOpen] = useState(false);
  const [copied, setCopied] = useState(null);

  const filledGoals = GOAL_FIELDS.filter((f) => (plan[f.key] || "").trim()).length;
  const decisionsLen = (plan.decisions || "").trim().length;
  const isComplete = filledGoals === GOAL_FIELDS.length;

  const aiPrompt = useMemo(() => fillPrompt(buildAIPrompt(profile), profile), [profile]);

  const setField = (key) => (e) => {
    onChange({ ...plan, [key]: e.target.value });
  };

  const handleCopyPrompt = () => {
    navigator.clipboard.writeText(aiPrompt).then(() => {
      setCopied("prompt");
      setTimeout(() => setCopied(null), 2000);
    });
  };

  const handleDownload = () => {
    downloadPlan(profile, plan);
    setCopied("download");
    setTimeout(() => setCopied(null), 2000);
  };

  return (
    <div className={`plan-card ${open ? "plan-card--open" : ""} ${isComplete ? "plan-card--complete" : ""}`}>
      <div className="plan-card__header" onClick={() => setOpen(!open)}>
        <div className="plan-card__header-left">
          <span className="plan-card__badge">
            {isComplete ? "✅ Plan complete" : hasGoals(plan) || decisionsLen ? "📋 Plan in progress" : "📋 Your Plan & Goals"}
          </span>
          <h3 className="plan-card__title">Plan, Decisions & 6-Month Goals</h3>
          <p className="plan-card__sub">
            {decisionsLen > 0 || filledGoals > 0
              ? `${decisionsLen.toLocaleString()} chars in Decisions · ${filledGoals}/5 milestone goals filled`
              : "Capture decisions in one place + set 30 / 60 / 90 / 120 / 180-day milestone goals."}
          </p>
        </div>
        <span className={`chevron ${open ? "chevron--up" : ""}`}>▾</span>
      </div>

      {open && (
        <div className="plan-card__body">
          {/* Decisions log */}
          <div className="plan-card__block">
            <div className="plan-card__block-label">📌 Decisions Log</div>
            <p className="plan-card__block-hint">
              Jot decisions, drop links, write reminders. One spot for everything you don't want to lose track of across all sections. Included in your Custom GPT brief so the consultant knows your context.
            </p>
            <textarea
              className="plan-card__textarea"
              value={plan.decisions || ""}
              rows={6}
              placeholder={`Examples:\n• Chose DesertEats over the other 9 ideas because nursing students were the only group who said "yes I'd pay" in interviews\n• Pricing: $25/wk subscription (not one-time) — recurring beats one-shot for cash flow\n• Decided to test on Discord first, not Instagram (where nursing students actually hang out)`}
              onChange={setField("decisions")}
            />
          </div>

          {/* 5 timeframe goals */}
          <div className="plan-card__block">
            <div className="plan-card__block-label">🎯 6-Month Milestone Goals</div>
            <p className="plan-card__block-hint">
              Five honest milestones — what's true at each stage if you stay on track. Day 180 is the $1,000/month target. Use the AI prompt below if you want a draft to start from.
            </p>

            <div className="plan-card__ai">
              <strong>🤖 Need a starting point?</strong>
              <p>Send this prompt to ChatGPT or Claude — it'll draft all 5 milestones based on your venture profile. Paste the result back into the boxes below (or directly into Decisions).</p>
              <div className="plan-card__ai-actions">
                <button
                  className={`copy-btn ${copied === "prompt" ? "copy-btn--copied" : ""}`}
                  onClick={handleCopyPrompt}
                >
                  {copied === "prompt" ? "✓ Copied!" : "📋 Copy AI prompt"}
                </button>
                <a
                  className="open-ai-btn open-ai-btn--chatgpt"
                  href={chatGPTUrl(aiPrompt)}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open in ChatGPT ↗
                </a>
                <a
                  className="open-ai-btn open-ai-btn--claude"
                  href={claudeUrl(aiPrompt)}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Open in Claude ↗
                </a>
              </div>
            </div>

            <div className="plan-card__goals">
              {GOAL_FIELDS.map((f) => (
                <div key={f.key} className="plan-card__goal">
                  <label className="plan-card__goal-label">{f.label}</label>
                  <p className="plan-card__goal-hint">{f.hint}</p>
                  <textarea
                    className="plan-card__textarea plan-card__textarea--goal"
                    value={plan[f.key] || ""}
                    rows={3}
                    placeholder={f.placeholder}
                    onChange={setField(f.key)}
                  />
                </div>
              ))}
            </div>
          </div>

          {/* Download */}
          <div className="plan-card__footer">
            <button
              className={`plan-card__download-btn ${copied === "download" ? "plan-card__download-btn--just-downloaded" : ""}`}
              onClick={handleDownload}
            >
              {copied === "download" ? "✓ Downloaded!" : "⬇ Download Plan.md"}
            </button>
            <span className="plan-card__footer-hint">
              💾 Also auto-saved in your browser and included in your Custom GPT brief.
            </span>
          </div>
        </div>
      )}
    </div>
  );
}
